### ISSUE TITLE
Zawartość mogłaby mieć 95vh.

### ISSUE THREAD

**Issue by Rednaxela700** [infoshareacademy/jfdd13-dreamteam-app#6]
Sprawdźcie wysokość swoich sekcji. Mam wrażenie, że wysokość kontenerów musimy ustawić inlineowo. 

PS. Z tego co pamiętam to demo jest w rozdzielczości 2560 na bodajże 1440. Nie mówię, że na taki ekran powinniśmy pisać, tylko że będzie słabo jeśli treść aplikacji zajmie 30% ekranu 

_Originally posted by @Rednaxela700 in https://github.com/infoshareacademy/jfdd13-dreamteam-app/pull/4#issuecomment-556642929_

**Comment by michal-kusnierz** [comment]
jeśli na demo będzie taka rozdzielczość, to zdecydowanie musimy wyrazić wielkość głównych (kontenerowych) komponentów w **vw** i **vh**

**Comment by Rednaxela700** [comment]
Z pomocą Kacpra udało się ustawić layout. Na demo postaram się ustawić rozdzielczość taką jaką mamy u nas. Zamykam.
